### ISSUE TITLE
[Bug]: onRequestPermissionsResult is called without results. Notification permission popup don't show up

### ISSUE THREAD

**Issue by raphaaell** [Baseflow/flutter-permission-handler#1190]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android (API version 33)
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Using 
`Permission.notification.isDenied.then((value) {`
`      if(value) {`
`            Permission.notification.request();`
`      }`
Notification request menu not showing up.

### Expected results

The notification request popup is supposed to show.

### Actual results

I got a warning in the debug console :

<details><summary>Warning in console</summary>

```console

onRequestPermissionsResult is called without results. This is probably caused by interfering request codes.
If you see this error, please file an issue in flutter-permission-handler, including a list of plugins used by this application: https://github.com/Baseflow/flutter-permission-handler/issues

```
</details>

And the popup don't show up

### Code sample

<details><summary>Code sample</summary>

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Permission.notification.isDenied.then((value) {
    if (value) {
      Permission.notification.request(); // Request notification with Permission handler | Not working
    }
  });
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  setupLocator();
  await NotificationsApi().requestPermission(); // Request notification with Firebase messaging | Not working
  runApp(const MyApp());
}
```

</details>

### Version

11.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [version 10.0.19045.3570], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

### Dependencies pubspec.yaml
<details><summary>Dependencies of pubspec.yaml</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  ###
  ### REQUESTS
  ###
  http: ^1.0.0
  path: ^1.8.3
  intl: ^0.18.0
  url_launcher: ^6.1.14

  ###
  ### ROUTER
  ###
  go_router: ^8.0.3

  ###
  ### FONTS
  ###

  # https://pub.dev/packages/google_fonts
  google_fonts: ^5.1.0

  ###
  ### STRUCTURE
  ###
  flutter_bloc: ^8.1.3
  freezed: ^2.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  ###
  ### SAVE IN LOCAL
  ###
  shared_preferences: ^2.1.2
  

  ###
  ### FIREBASE
  ###
  firebase_core: ^2.14.0

  ###
  ### NOTIFICATIONS
  ###
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  
  ###
  ### MAPS
  ###
  google_maps_flutter: ^2.5.0

  ###
  ### IMAGE
  ###
  image_picker: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.3
  
  ###
  ### OTHERS
  ###
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
```

</details>

**Comment by tva77** [comment]
same here

**Comment by AbdallahAwd** [comment]
same on android 13

**Comment by IgorUniPro** [comment]
Аналогичная проблема с android 13

**Comment by fanpener** [comment]
same

**Comment by mvanbeusekom** [comment]
Hi @raphaaell , @AbdallahAwd , @IgorUniPro  and @fanpener,

The log message shown is caused in two situations:

1. Other plugins also subscribed to Androids `onRequestPermissionsResult` callback and use the same `requestCode` as the permission_handler (which is `24`).
2. The `Permission.notification.request` method is called multiple times in rapid succession (one example of when this might happen is when called from a `build` method in a widget).

I have checked all dependencies mentioned in the issue created by @raphaaell and couldn't find a dependency which uses the same `requestCode` so (at least in @raphaaell's case) situation 1 is ruled out. This leaves situation 2, I noticed that the call to `Permission.notification.request` is not awaited which is a first warning of a potential error. 

I have tried to reproduce the error in a new Flutter application, but cannot reproduce the error. The code I used is shown below.

<details>
<summary>lib/main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    Permission.notification.isDenied.then((bool isGranted) async {
      print('==DEBUG==: Requesting permission.');
      final PermissionStatus status = await Permission.notification.request();
      print('==DEBUG==: New status: $status');
    });

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details> 

<details>
<summary>pubspec.yaml</summary>

```yaml
name: ph_issue_1190
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  ###
  ### REQUESTS
  ###
  http: ^1.0.0
  path: ^1.8.3
  intl: ^0.18.0
  url_launcher: ^6.1.14

  ###
  ### ROUTER
  ###
  go_router: ^8.0.3

  ###
  ### FONTS
  ###

  # https://pub.dev/packages/google_fonts
  google_fonts: ^5.1.0

  ###
  ### STRUCTURE
  ###
  flutter_bloc: ^8.1.3
  freezed: ^2.3.2
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  ###
  ### SAVE IN LOCAL
  ###
  shared_preferences: ^2.1.2
  

  ###
  ### FIREBASE
  ###
  firebase_core: ^2.14.0

  ###
  ### NOTIFICATIONS
  ###
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  
  ###
  ### MAPS
  ###
  google_maps_flutter: ^2.5.0

  ###
  ### IMAGE
  ###
  image_picker: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.3
  
  ###
  ### OTHERS
  ###
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

</details>

<details>
<summary>android/app/src/main/AndroidManifest.xml</summary>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Permissions options for the `access notification policy` group -->
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>

    <!-- Permissions options for the `notification` group -->
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>

    <application
        android:label="ph_issue_1190"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```
</details>

The output of the application (when I hit the `+` button) is:

```
I/flutter ( 4162): ==DEBUG==: Requesting permission.
I/flutter ( 4162): ==DEBUG==: New status: PermissionStatus.granted
```

Since I am unable to reproduce this issue and everything seems to work on my side I will reluctantly go ahead and close this issue for now. I would be happy to reopen the issue if anyone can create a small example application demonstrating the error.
