### ISSUE TITLE
Requesting activity recognition permission doesn't prompt for any permission in iOS devices.

### ISSUE THREAD

**Issue by bikcrum** [Baseflow/flutter-permission-handler#379]
## 🐛 Bug Report

Requesting activity recognition permission doesn't prompt for any permission in iOS devices.

### Expected behavior

Like in Android devices, iOS devices should have asked for activity recognition permission with a dialog. Permission status is always undetermined when requesting.

### Reproduction steps

```
var status = await Permission.activityRecognition.request();
// check value of status. It's always coming PermissionStatus.undetermined.
// No prompt in iOS device
// Only works with Android device
```

### Configuration

**pubspec.lock**
```
...
 permission_handler:
    dependency: "direct main"
    description:
      name: permission_handler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.1+1"
  permission_handler_platform_interface:
    dependency: transitive
    description:
      name: permission_handler_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
...
```

**Platform:** 
- Device model: iPhone 6, iOS 12.4.8
