### ISSUE TITLE
Permission handler in flutter(Dart)

### ISSUE THREAD

**Issue by Usman167** [Baseflow/flutter-permission-handler#494]
How to get internal mobile storage permission in flutter?
My files are:
**Dart code file** 

```dart
import 'package:permission_handler/permission_handler.dart';

void initState(){
  getPermission(); 
}
                
void getPermission() async {
  await PermissionHandler().requestPermissions([PermissionGroup.storage]);
}
``` 

**Android Menifest.xml**

```xml
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**pubspec.yaml**
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_downloader: ^1.5.2
  ext_storage: ^1.0.3
  permission_handler: ^6.1.1
  dio: ^3.0.10
```

**Error**
'PermissionHandler'  and PermissionGroup are both are undefined

The method 'PermissionHandler' isn't defined for the type '_MyPdfState'.
Try correcting the name to the name of an existing method, or defining a method named 'PermissionHandler'.dartundefined_method

Undefined name 'PermissionGroup'.
Try correcting the name to one that is defined, or defining the name.
